import { useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Itinerary } from '../types/itinerary';

interface PDFExportProps {
  itinerary: Itinerary;
}

function PDFExport({ itinerary }: PDFExportProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    setIsGenerating(true);

    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();

      // Title
      pdf.setFontSize(24);
      pdf.setTextColor(232, 93, 4); // forge-orange
      pdf.text(itinerary.tripTitle, 20, 30);

      // Subtitle
      pdf.setFontSize(12);
      pdf.setTextColor(100);
      pdf.text(
        `${itinerary.destination} • ${itinerary.days.length} days • Est. ${itinerary.totalEstimatedCost} ${itinerary.currency}`,
        20,
        40
      );

      // Days
      let yPosition = 60;

      itinerary.days.forEach((day, index) => {
        // Check if we need a new page
        if (yPosition > 250) {
          pdf.addPage();
          yPosition = 30;
        }

        // Day header
        pdf.setFontSize(16);
        pdf.setTextColor(13, 27, 42); // forge-navy
        pdf.text(`Day ${day.day}: ${day.theme}`, 20, yPosition);
        yPosition += 10;

        // Activities
        pdf.setFontSize(11);
        pdf.setTextColor(80);

        ['Morning', 'Afternoon', 'Evening'].forEach((period) => {
          const activity =
            period === 'Morning'
              ? day.morning
              : period === 'Afternoon'
              ? day.afternoon
              : day.evening;

          pdf.text(`${period}: ${activity.activity}`, 25, yPosition);
          yPosition += 6;
          pdf.setFontSize(9);
          pdf.text(`  ${activity.location} • ${activity.duration}`, 25, yPosition);
          pdf.setFontSize(11);
          yPosition += 8;
        });

        // Meals
        pdf.text('Meals:', 25, yPosition);
        yPosition += 6;
        pdf.setFontSize(9);
        pdf.text(
          `  Breakfast: ${day.meals.breakfast.name} (${day.meals.breakfast.priceRange})`,
          25,
          yPosition
        );
        yPosition += 5;
        pdf.text(
          `  Lunch: ${day.meals.lunch.name} (${day.meals.lunch.priceRange})`,
          25,
          yPosition
        );
        yPosition += 5;
        pdf.text(
          `  Dinner: ${day.meals.dinner.name} (${day.meals.dinner.priceRange})`,
          25,
          yPosition
        );
        yPosition += 5;

        // Insider tip
        pdf.setTextColor(232, 93, 4);
        pdf.text(`Tip: ${day.insiderTip}`, 25, yPosition);
        pdf.setTextColor(80);
        yPosition += 15;
      });

      // Footer
      const pageCount = pdf.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(10);
        pdf.setTextColor(150);
        pdf.text(
          'Generated by Tripforge • tripforge.com',
          pageWidth / 2,
          285,
          { align: 'center' }
        );
      }

      pdf.save(`${itinerary.tripTitle.replace(/\s+/g, '_')}_itinerary.pdf`);
    } catch (error) {
      console.error('Failed to generate PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={isGenerating}
      className="btn-secondary flex items-center gap-2"
    >
      <svg
        className="w-5 h-5"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
        />
      </svg>
      {isGenerating ? 'Generating...' : 'Export PDF'}
    </button>
  );
}

export default PDFExport;
